
========================================================================

**Graded Challenge 3**

Nama  : Iznia Azyati

Batch : RMT-032

Program ini dibuat untuk melakukan sesuai dengan konsep Web Scraping, 
Business Knowledge dengan dengan framework SMART, dan Practical Statistics 
untuk melakukan pengujian statistik dan merumuskan hipotesis. 

========================================================================


### **Case**

PT. ABCD ingin menambah pendapatan dengan berjualan. Namun, perusahaan tidak punya cukup modal untuk produksi barang dan hanya cukup untuk promosi, sehingga perusahaan memutuskan untuk menjalanan skema dropship di platform Tokopedia.

Tetapi, perusahaan masih bingung akan berjualan apa dan teringat bahwa saat ini sedang viral seblak. Namun, perusahaan tidak yakin apakah benar bahwa masyarakat memiliki animo yang besar terhadap seblak.

Maka dari itu diperlukan analisis mengenai bagaimana penjualan produk seblak di Tokopedia. Apakah orang suka, apakah banyak yang beli, dsb.

Tantangannya, perusahaan tidak punya data sama sekali selain yang terpampang pada website e-commerce Tokopedia. Oleh karena itu, diperlukan pengambilan data terlebih dahulu menggunakan Web Scraping.

Langkah-langkah yang perlu dilakukan adalah:


### Install bs4 dan Selenium

In [1]:
!pip install bs4 selenium

### Akses Website

In [2]:
!pip install requests

### A. Web Scraping

#### 1. Pengambilan data dari URL

In [1]:
import requests


page = requests.get('https://www.tokopedia.com/search?navsource=&page=1&q=seblak&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st=')
page

#### Persiapan

#### --Merancang URL Pencarian--

In [6]:
# Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import time

In [7]:
# buat driver 

driver = webdriver.Chrome()

#setelah di running akan membuat browser dengan sendirinya

In [8]:
# untuk akses website, sediakan url
# URL halaman pencarian Tokopedia untuk "Seblak"
url = 'https://www.tokopedia.com/search?navsource=&page=1&q=seblak&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st='

# akses website
driver.get(url)

In [9]:
# extract html
html = driver.page_source

In [10]:
#isi html
html

'<html lang="id" translate="no" data-rh="lang,translate"><head>\n    <title>Jual seblak | Tokopedia</title>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="initial-scale=1, minimum-scale=1, maximum-scale=5, user-scalable=yes, width=device-width">\n    <link rel="preconnect" href="https://assets.tokopedia.net" crossorigin=""><link rel="dns-prefetch" href="https://assets.tokopedia.net" nonce="">\n<link rel="preconnect" href="https://gql.tokopedia.com" crossorigin=""><link rel="dns-prefetch" href="https://gql.tokopedia.com" nonce="">\n<link rel="preconnect" href="https://googleads.g.doubleclick.net" crossorigin=""><link rel="dns-prefetch" href="https://googleads.g.doubleclick.net" nonce="">\n<link rel="preconnect" href="https://www.google-analytics.com" crossorigin=""><link rel="dns-prefetch" href="https://www.google-analytics.com" nonce="">\n<link rel="preconnect" href="https://images.tokopedia.net" crossorigin=""><link rel="dns-prefetch" href="https://images.tokopedia.ne

In [11]:
# Parsing html
soup = BeautifulSoup(html, 'html.parser')

soup

<html data-rh="lang,translate" lang="id" translate="no"><head>
<title>Jual seblak | Tokopedia</title>
<meta charset="utf-8"/>
<meta content="initial-scale=1, minimum-scale=1, maximum-scale=5, user-scalable=yes, width=device-width" name="viewport"/>
<link crossorigin="" href="https://assets.tokopedia.net" rel="preconnect"/><link href="https://assets.tokopedia.net" nonce="" rel="dns-prefetch"/>
<link crossorigin="" href="https://gql.tokopedia.com" rel="preconnect"/><link href="https://gql.tokopedia.com" nonce="" rel="dns-prefetch"/>
<link crossorigin="" href="https://googleads.g.doubleclick.net" rel="preconnect"/><link href="https://googleads.g.doubleclick.net" nonce="" rel="dns-prefetch"/>
<link crossorigin="" href="https://www.google-analytics.com" rel="preconnect"/><link href="https://www.google-analytics.com" nonce="" rel="dns-prefetch"/>
<link crossorigin="" href="https://images.tokopedia.net" rel="preconnect"/><link href="https://images.tokopedia.net" nonce="" rel="dns-prefetch"/>


In [12]:

# Buat list untuk menampung nilai 
list_nama = []
list_harga = []
list_penjual = []
list_kota_toko = []
list_terjual = []
list_rating =[]

# HASILNYA AKAN ME-RELOAD chrome link itu dari halaman 1-10.

# Looping halaman 1-10
for halaman in range(1, 11):
    # sediakan url
    url = f'https://www.tokopedia.com/search?navsource=&page={halaman}&q=seblak&srp_component_id=02.01.00.00&srp_page_id=&srp_page_title=&st='

    # akses website
    driver.get(url)

    # proses loading
    time.sleep(3)       # Tambahkan sedikit waktu untuk makesure halaman dimuat.

    # extract html
    html = driver.page_source

    # Parsing html
    soup = BeautifulSoup(html, 'html.parser')


    # Mengumpulkan box/container items
    items = soup.find_all('div', {'class':'css-1asz3by'})

    # Akses nilai tiap kotak (nama, harga, penjual, kota toko, banyaknya terjual, dan rating)
    for item in items:

        # Mengambil nama produk
        try:
            nama_produk = item.find('div', {'class':'css-3um8ox'}).get_text()
            list_nama.append(nama_produk)
        except:
            list_nama.append(None)

        # Mengambil harga produk 
        try:
            harga_produk = item.find('div', {'class':'css-h66vau'}).get_text()
            list_harga.append(harga_produk)
        except:
            list_harga.append(None)
        

        # Mengambil kota toko 
        try:
            kota_toko = item.find('span', {'class':'prd_link-shop-loc css-1kdc32b flip'}).text if item.find('span', {'class':'prd_link-shop-loc css-1kdc32b flip'}) else None
            list_kota_toko.append(kota_toko)
        except:
            list_kota_toko.append(None)

        # Mengambil penjual 
        try:
            penjual = item.find('span', {'class':'prd_link-shop-name css-1kdc32b flip'}).text if item.find('span', {'class':'prd_link-shop-name css-1kdc32b flip'}) else None
            list_penjual.append(penjual)
        except:
            list_penjual.append(None)


        # Mengambil banyaknya terjual 
        try:
            terjual = item.find('span', {'class':'css-1sgek4h'}).get_text().split(' ')[0]
            list_terjual.append(terjual)
        except:
            list_terjual.append(None)

        # Mengambil rating 
        try:
            rating = item.find('span', {'class':'css-t70v7i'}).get_text()
            if rating:
                list_rating.append(rating)
            else:
                rating = None
        except:
            list_rating.append(None)



In [13]:
# Gabungkan list menjadi dataframe
data = pd.DataFrame({
    'Nama Produk': list_nama,
    'Harga Produk' : list_harga,
    'Kota Toko' : list_kota_toko,
    'Penjual' : list_penjual,
    'Banyaknya Terjual' : list_terjual,
    'Rating' : list_rating})

# Panggil datanya
data


Nama Produk Harga Produk  \
0                                  Kylafood Seblak Cup      Rp9.730   
1                                       Seblak Karuhun     Rp12.825   
2                              Kylafood Seblak karuhun      Rp9.450   
3                           SEBLAK INSTAN SAJODO SNACK     Rp18.500   
4               Seblak Rafael/Seblak Coet Instan Halal     Rp26.600   
..                                                 ...          ...   
356             Seblak pedas kerupuk pedas kiloan 1 kg     Rp34.000   
357  Kerupuk Seblak Rafael Pedas / Seblak Mawar Ped...     Rp16.000   
358  KERUPUK SEBLAK MINI KENCUR JABLAY BANTET PEDAS...     Rp23.000   
359                      Seblak Instan Pedas Home Made      Rp3.500   
360             Krupuk seblak mawar rafael pedas 500gr     Rp23.500   

             Kota Toko              Penjual Banyaknya Terjual Rating  
0                 None                 None              250+    4.8  
1                 None                 None               60+    5.0  
2                 None                 None                 4    4.8  
3          Tasikmalaya  Sajodo Snack & Food              100+    4.7  
4      Jakarta Selatan           Foodstocks              100+    5.0  
..                 ...                  ...               ...    ...  
356         Kab. Bogor        RIKI STORE 97              100+    4.7  
357              Depok      DUO BOCIL SNACK              250+    4.9  
358      Jakarta Utara  ajs(ale jaya snack)               40+    4.9  
359  Tangerang Selatan           the Dhecip              3rb+    4.9  
360        Kab. Bekasi      Markas Makaroni              100+    4.9  

[361 rows x 6 columns]

In [14]:
# Menyimpan DataFrame ke CSV
data.to_csv('data_tokopedia_seblak.csv', index=False)
print("Data berhasil disimpan ke file data_tokopedia_seblak.csv")


Data berhasil disimpan ke file data_tokopedia_seblak.csv


In [18]:
# Tampilkan data untuk verifikasi
data.head(10)


Nama Produk Harga Produk  \
0                                Kylafood Seblak Cup      Rp9.730   
1                                     Seblak Karuhun     Rp12.825   
2                            Kylafood Seblak karuhun      Rp9.450   
3                         SEBLAK INSTAN SAJODO SNACK     Rp18.500   
4             Seblak Rafael/Seblak Coet Instan Halal     Rp26.600   
5  Kerupuk seblak kering 500 gram extra pedas /se...     Rp24.700   
6  Seblak Instan Ceu Nthien Khas Bandung Rasana N...     Rp17.000   
7                                SEBLAK INSTAN MOMMY     Rp13.900   
8                      Seblak Instan Pedas Home Made      Rp3.500   
9             Seblak pedas kerupuk pedas kiloan 1 kg     Rp34.000   

           Kota Toko                   Penjual Banyaknya Terjual Rating  
0               None                      None              250+    4.8  
1               None                      None               60+    5.0  
2               None                      None                 4    4.8  
3        Tasikmalaya       Sajodo Snack & Food              100+    4.7  
4    Jakarta Selatan                Foodstocks              100+    5.0  
5      Jakarta Barat              oyun kriukzz               40+    4.8  
6  Tangerang Selatan  Central Seblak Nusantara              2rb+    4.9  
7     Kab. Tangerang          Rav Jaya Display              1rb+    4.8  
8  Tangerang Selatan                the Dhecip              3rb+    4.9  
9         Kab. Bogor             RIKI STORE 97              100+    4.7

In [19]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Nama Produk        361 non-null    object
 1   Harga Produk       361 non-null    object
 2   Kota Toko          340 non-null    object
 3   Penjual            340 non-null    object
 4   Banyaknya Terjual  350 non-null    object
 5   Rating             341 non-null    object
dtypes: object(6)
memory usage: 17.1+ KB
None


In [21]:
# Menampilkan DataFrame
data

Nama Produk Harga Produk  \
0                                  Kylafood Seblak Cup      Rp9.730   
1                                       Seblak Karuhun     Rp12.825   
2                              Kylafood Seblak karuhun      Rp9.450   
3                           SEBLAK INSTAN SAJODO SNACK     Rp18.500   
4               Seblak Rafael/Seblak Coet Instan Halal     Rp26.600   
..                                                 ...          ...   
356             Seblak pedas kerupuk pedas kiloan 1 kg     Rp34.000   
357  Kerupuk Seblak Rafael Pedas / Seblak Mawar Ped...     Rp16.000   
358  KERUPUK SEBLAK MINI KENCUR JABLAY BANTET PEDAS...     Rp23.000   
359                      Seblak Instan Pedas Home Made      Rp3.500   
360             Krupuk seblak mawar rafael pedas 500gr     Rp23.500   

             Kota Toko              Penjual Banyaknya Terjual Rating  
0                 None                 None              250+    4.8  
1                 None                 None               60+    5.0  
2                 None                 None                 4    4.8  
3          Tasikmalaya  Sajodo Snack & Food              100+    4.7  
4      Jakarta Selatan           Foodstocks              100+    5.0  
..                 ...                  ...               ...    ...  
356         Kab. Bogor        RIKI STORE 97              100+    4.7  
357              Depok      DUO BOCIL SNACK              250+    4.9  
358      Jakarta Utara  ajs(ale jaya snack)               40+    4.9  
359  Tangerang Selatan           the Dhecip              3rb+    4.9  
360        Kab. Bekasi      Markas Makaroni              100+    4.9  

[361 rows x 6 columns]

### B. Data Preparation
#### 1. Eksplorasi data sederhana:
- Tampilkan beberapa baris data - tuliskan insight.
- Tampilkan informasi rangkuman data - tuliskan insight dan berikan penjelasan langkah apa yang akan kamu lakukan.
- Cek missing value - tuliskan insight dari temuan yang kamu dapatkan

A. Tampilkan beberapa baris data

Ini untuk menampilkan beberapa baris dari data yang telah kita scrape.

In [22]:
import pandas as pd

# Membaca data dari file CSV yang telah disimpan
data = pd.read_csv('data_tokopedia_seblak.csv')

# Menampilkan beberapa baris pertama dari data
data.head(10)


Nama Produk Harga Produk  \
0                                Kylafood Seblak Cup      Rp9.730   
1                                     Seblak Karuhun     Rp12.825   
2                            Kylafood Seblak karuhun      Rp9.450   
3                         SEBLAK INSTAN SAJODO SNACK     Rp18.500   
4             Seblak Rafael/Seblak Coet Instan Halal     Rp26.600   
5  Kerupuk seblak kering 500 gram extra pedas /se...     Rp24.700   
6  Seblak Instan Ceu Nthien Khas Bandung Rasana N...     Rp17.000   
7                                SEBLAK INSTAN MOMMY     Rp13.900   
8                      Seblak Instan Pedas Home Made      Rp3.500   
9             Seblak pedas kerupuk pedas kiloan 1 kg     Rp34.000   

           Kota Toko                   Penjual Banyaknya Terjual  Rating  
0                NaN                       NaN              250+     4.8  
1                NaN                       NaN               60+     5.0  
2                NaN                       NaN                 4     4.8  
3        Tasikmalaya       Sajodo Snack & Food              100+     4.7  
4    Jakarta Selatan                Foodstocks              100+     5.0  
5      Jakarta Barat              oyun kriukzz               40+     4.8  
6  Tangerang Selatan  Central Seblak Nusantara              2rb+     4.9  
7     Kab. Tangerang          Rav Jaya Display              1rb+     4.8  
8  Tangerang Selatan                the Dhecip              3rb+     4.9  
9         Kab. Bogor             RIKI STORE 97              100+     4.7

**Insight:**

- Dari 10 baris pertama data ini, kita dapat melihat bahwa nama produk dan harga tersedia untuk semua produk.
- Namun, beberapa kolom seperti Kota Toko, Banyaknya Terjual, dan Rating mungkin memiliki nilai yang hilang (None/NaN).

B. Tampilkan informasi rangkuman data 

Untuk melihat informasi rangkuman data untuk memahami tipe data dan jumlah nilai yang hilang di setiap kolom.


In [23]:
# Menampilkan informasi rangkuman data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Nama Produk        361 non-null    object 
 1   Harga Produk       361 non-null    object 
 2   Kota Toko          340 non-null    object 
 3   Penjual            340 non-null    object 
 4   Banyaknya Terjual  350 non-null    object 
 5   Rating             341 non-null    float64
dtypes: float64(1), object(5)
memory usage: 17.1+ KB


**Insight:**
1. Jumlah Data: Dataset memiliki 361 baris data dengan 6 kolom.
2. Missing Values:
Ada beberapa kolom yang memiliki nilai yang hilang, terutama di kolom "Kota Toko", "Penjual", "Banyaknya Terjual", dan "Rating".

3. Tipe Data: 
- Kolom "Harga Produk" dan "Banyaknya Terjual" bertipe object padahal seharusnya bertipe numerik.
- Kolom "Rating" bertipe float, yang sesuai untuk analisis lebih lanjut.

Langkah selanjutnya adalah melakukan **data cleaning** untuk menangani missing values dan memastikan tipe data konsisten.

C. Cek Missing Value


In [24]:
# Mengecek missing value
missing_values = data.isnull().sum()
print(missing_values)

Nama Produk           0
Harga Produk          0
Kota Toko            21
Penjual              21
Banyaknya Terjual    11
Rating               20
dtype: int64


**Insight:**
1. Nama Produk dan Harga Produk: 
Tidak ada missing values pada kolom ini, yang berarti semua produk yang di-scrape memiliki informasi nama dan harga.
2. Kota Toko:
Ada 21 nilai yang hilang di kolom "Kota Toko". Hal ini bisa terjadi karena beberapa penjual tidak mengisi informasi kota toko mereka.
3. Penjual:
Sama seperti "Kota Toko", kolom "Penjual" juga memiliki 21 nilai yang hilang. Ini mungkin terjadi pada produk-produk yang berasal dari penjual yang sama yang tidak mengisi informasi kota atau karena penjual baru yang belum melengkapi profil mereka.
4. Banyaknya Terjual:
Ada 11 nilai yang hilang di kolom "Banyaknya Terjual". Hal ini kemungkinan besar terjadi pada produk baru yang belum ada penjualan.
5. Rating:
Ada 20 nilai yang hilang di kolom "Rating". Hal ini terjadi karena ada produk baru yang belum mendapatkan ulasan atau rating dari pembeli.

**Langkah yang Akan Dilakukan:**
1. Mengisi Missing Values:

    Kota Toko dan Penjual: Mengisi missing values dengan 'Unknown' untuk menunjukkan bahwa informasi ini tidak tersedia.

2. Banyaknya Terjual dan Rating: Mengisi missing values dengan 0 untuk menunjukkan bahwa produk ini mungkin baru dan belum ada penjualan atau rating.

### 2. Data Cleaning

A. Handle Missing Values

Akan mengganti missing values dengan nilai yang tepat (seperti 0 untuk banyaknya terjual dan rating)

Catatan: Pada kolom "Banyaknya Terjual", jumlah produk yang terjual dituliskan sebagai Terjual 750+, Terjual 1 rb. Ambil angkanya saja. Misal Terjual 750+ -> 750 dan Terjual 1 rb -> 1000.


In [25]:
# Mengganti missing values pada kolom "Banyaknya Terjual" dan "Rating" dengan 0
data['Banyaknya Terjual'] = data['Banyaknya Terjual'].fillna(0)
data['Rating'] = data['Rating'].fillna(0)

# Mengganti missing values pada kolom "Kota Toko" dan "Penjual" dengan 'Unknown'
data['Kota Toko'] = data['Kota Toko'].fillna('Unknown')
data['Penjual'] = data['Penjual'].fillna('Unknown')



B. Ubah Bentuk Data Menjadi Konsisten dan Menyesuaikan Tipe Data

Mengubah tipe data pada kolom "Harga Produk" dan "Banyaknya Terjual" menjadi numerik.

In [26]:
# Menghilangkan simbol-simbol non-numerik dan mengubah tipe data menjadi integer

# Mengubah kolom "Harga Produk" menjadi string, membersihkan simbol, lalu mengonversi ke integer
data['Harga Produk'] = data['Harga Produk'].astype(str)
data['Harga Produk'] = data['Harga Produk'].str.replace('Rp', '', regex=False).str.replace('.', '', regex=False).astype(int)

# Mengubah kolom "Banyaknya Terjual" menjadi string, membersihkan simbol, lalu mengonversi ke integer
data['Banyaknya Terjual'] = data['Banyaknya Terjual'].astype(str)
data['Banyaknya Terjual'] = data['Banyaknya Terjual'].str.replace(r'\+', '', regex=True).str.replace(' rb', '000', regex=False)

# Mengatasi nilai kosong atau tidak valid dan konversi ke integer
def convert_to_int(value):
    try:
        return int(value)
    except ValueError:
        return 0

data['Banyaknya Terjual'] = data['Banyaknya Terjual'].apply(convert_to_int)


**Penjelasan:**
- Menggunakan str.replace untuk menghapus karakter + dan mengganti rb dengan 000.
- Menambahkan fungsi convert_to_int untuk menangani nilai yang tidak valid dan mengonversinya ke 0.

Dengan ini, semua nilai dalam kolom "Banyaknya Terjual" yang tidak bisa langsung dikonversi akan diubah menjadi 0, sehingga mencegah error saat konversi tipe data.

In [27]:
# Menampilkan beberapa baris pertama dari data setelah di cleaning
data.head(10)


Nama Produk  Harga Produk  \
0                                Kylafood Seblak Cup          9730   
1                                     Seblak Karuhun         12825   
2                            Kylafood Seblak karuhun          9450   
3                         SEBLAK INSTAN SAJODO SNACK         18500   
4             Seblak Rafael/Seblak Coet Instan Halal         26600   
5  Kerupuk seblak kering 500 gram extra pedas /se...         24700   
6  Seblak Instan Ceu Nthien Khas Bandung Rasana N...         17000   
7                                SEBLAK INSTAN MOMMY         13900   
8                      Seblak Instan Pedas Home Made          3500   
9             Seblak pedas kerupuk pedas kiloan 1 kg         34000   

           Kota Toko                   Penjual  Banyaknya Terjual  Rating  
0            Unknown                   Unknown                250     4.8  
1            Unknown                   Unknown                 60     5.0  
2            Unknown                   Unknown                  4     4.8  
3        Tasikmalaya       Sajodo Snack & Food                100     4.7  
4    Jakarta Selatan                Foodstocks                100     5.0  
5      Jakarta Barat              oyun kriukzz                 40     4.8  
6  Tangerang Selatan  Central Seblak Nusantara                  0     4.9  
7     Kab. Tangerang          Rav Jaya Display                  0     4.8  
8  Tangerang Selatan                the Dhecip                  0     4.9  
9         Kab. Bogor             RIKI STORE 97                100     4.7

In [28]:
# Menampilkan informasi rangkuman data setelah di cleaning
data.info()

# Hasilnya sudah tidak ada missing value dan tipe datanya sudah sesuai

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Nama Produk        361 non-null    object 
 1   Harga Produk       361 non-null    int32  
 2   Kota Toko          361 non-null    object 
 3   Penjual            361 non-null    object 
 4   Banyaknya Terjual  361 non-null    int64  
 5   Rating             361 non-null    float64
dtypes: float64(1), int32(1), int64(1), object(3)
memory usage: 15.6+ KB


In [29]:
# Menyimpan data yang telah dibersihkan ke file CSV baru
data.to_csv('data_tokped_seblak_clean.csv', index=False)

### C. Business Understanding/Problem Statement

Buat problem statement menggunakan SMART framework berikut dengan penjabaran Specific, Measurable, Achievable, Relevant, dan Time-bound. Jangan lupa merangkup dalam satu kalimat problem statement serta gunakan metrik yang tepat dari kasus ini.

#### SMART Framework

**Problem**

Perusahaan ingin meningkatkan jumlah produk seblak yang terjual di Tokopedia dengan fokus pada peningkatan jumlah produk yang terjual sebanyak 15%.


**SMART**
1. Specific: 
 
    Ingin memahami faktor-faktor apa saja yang mempengaruhi penjualan produk seblak di Tokopedia dengan tujuan untuk meningkatkan volume penjualan (jumlah produk terjual) sebesar 15%.


2. Measurable: 

    Keberhasilan akan diukur dengan peningkatan persentase jumlah unit produk seblak yang terjual dan peningkatan rata-rata rating produk di Tokopedia setelah mengimplementasikan strategi.


3. Achievable: 

    Analisis dan strategi didasarkan pada data historis penjualan seblak yang sudah ada di Tokopedia, sehingga hal ini memungkinkan kami mendapatkan pengetahuan yang bisa diterapkan.


4. Relevant: 

    Dengan menganalisis dan mengimplementasikan strategi diatas, untuk meningkatkan penjualan seblak adalah penting/relevan bagi kami(penjual) untuk meningkatkan pendapatan dan memperkuat posisi kami di pasar e-commerce (baik di Tokopedia maupun di platform e-commerce lain).


5. Time-bound: 

    Target ini akan dicapai dalam waktu 2 bulan, dimulai dari pengumpulan data, analisis data, sampai implementasi strategi dan evaluasi hasilnya.



**Problem Statement:**

"Dalam waktu 2 bulan, kami akan meningkatkan jumlah produk seblak di Tokopedia sebesar 15% dan meningkatkan rata-rata rating produk sebesar 0.5 poin melalui analisis data historis dan penerapan strategi yang relevan, sehingga kami mengetahui faktor-faktor penentu penjualan dan menerapkan strategi yang sesuai."


Metrik:

1. Jumlah Produk Terjual: Mengukur total unit produk seblak yang terjual sebelum dan sesudah mengimplementasikan SMART diatas.
2. Rating Produk: Mengukur perubahan rata-rata rating produk sebelum dan sesudah implementasi strategi.
3. Persentase Peningkatan Penjualan: ((Penjualan setelah implementasi - Penjualan sebelum implementasi) / Penjualan sebelum implementasi) * 100.
4. Peningkatan Rata-rata Rating: Rata-rata rating setelah implementasi - Rata-rata rating sebelum implementasi.

### D. Analysis 

**Analisis ini membutuhkan beberapa langkah:**
1. Pengumpulan data. Mengambil data produk seblak dari Tokopedia selama periode tertentu.
2. Pembersihan Data: Mengganti nilai yang hilang dan mengubah tipe data.
3. Perhitungan Statistik Deskriptif: Menghitung rata-rata, median, standar deviasi, skewness, dan kurtosis untuk kolom harga, banyaknya terjual, dan rating.
4. Analisis Distribusi: Menggunakan hasil statistik untuk mendapatkan insight mengenai distribusi harga, banyaknya terjual, dan rating, serta mengidentifikasi adanya outlier.
5. Estimasi Pendapatan: Menghitung potensi pendapatan minimum dan maksimum menggunakan interval kepercayaan (confidence interval) dari distribusi populasi pendapatan.

Notes: *Poin 1 dan 2 sudah dilakukan diawal. 

#### Perhitungan Statistik Deskriptif

In [33]:
# Import Libraries
# scipy.stat utnuk mneghitung nilai skewness dan kurtosis dari data yang ada

import pandas as pd
from scipy.stats import skew, kurtosis

# Membaca data dari file CSV yang telah dibersihkan
data = pd.read_csv('data_tokped_seblak_clean.csv')


In [36]:
# Menghitung statistik deskriptif (rata-rata, median, standar deviasi, skewness, dan kurtosis) 

# Dihitung dari kolom harga, banyaknya produk terjual, dan rating. 

columns = ['Harga Produk', 'Banyaknya Terjual', 'Rating']
stats = {}

for col in columns:
    stats[col] = {
        'Mean': data[col].mean(),
        'Median': data[col].median(),
        'Standard Deviation': data[col].std(),
        'Skewness': skew(data[col]),
        'Kurtosis': kurtosis(data[col])
    }

# Membuat DataFrame dari hasil statistik
stats_data = pd.DataFrame(stats)
print(stats_data)

                    Harga Produk  Banyaknya Terjual     Rating
Mean                21367.454294         160.842105   4.608864
Median              16000.000000          80.000000   4.900000
Standard Deviation  48757.801406         207.408025   1.121397
Skewness               11.964782           1.360124  -3.844934
Kurtosis              151.025169           0.647494  12.900561


In [37]:
# Tampilkan data
stats_data

Harga Produk  Banyaknya Terjual     Rating
Mean                21367.454294         160.842105   4.608864
Median              16000.000000          80.000000   4.900000
Standard Deviation  48757.801406         207.408025   1.121397
Skewness               11.964782           1.360124  -3.844934
Kurtosis              151.025169           0.647494  12.900561

In [38]:
# Analisis hasilnya
for col in columns:
    print(f"--- {col} ---")
    print(f"Mean: {stats_data.loc['Mean', col]}")
    print(f"Median: {stats_data.loc['Median', col]}")
    print(f"Standard Deviation: {stats_data.loc['Standard Deviation', col]}")
    print(f"Skewness: {stats_data.loc['Skewness', col]}")
    print(f"Kurtosis: {stats_data.loc['Kurtosis', col]}")
    print()


--- Harga Produk ---
Mean: 21367.45429362881
Median: 16000.0
Standard Deviation: 48757.80140584618
Skewness: 11.964782295450748
Kurtosis: 151.0251693345549

--- Banyaknya Terjual ---
Mean: 160.8421052631579
Median: 80.0
Standard Deviation: 207.408025131355
Skewness: 1.3601242192120457
Kurtosis: 0.6474942337384517

--- Rating ---
Mean: 4.608864265927977
Median: 4.9
Standard Deviation: 1.121397484229475
Skewness: -3.844934182411999
Kurtosis: 12.900560972841207



#### **Insight dari hasil perhitungan**

*--- Harga Produk ---*
- Mean (Rata-rata): Rp 21.367
- Median: Rp 16.000
- Standar Deviasi: Rp 48.757
- Skewness: 11.96
- Kurtosis: 151.03


*Insight:*
1. Distribusi: Harga produk memiliki distribusi yang sangat tidak simetris (positively skewed) dengan skewness sebesar 11.96. Ini menunjukkan bahwa sebagian besar harga produk berada di bawah rata-rata, dengan beberapa produk yang harganya jauh lebih tinggi yang menaikkan rata-rata.
2. Outlier: Kurtosis yang sangat tinggi (151.03) menunjukkan adanya outlier ekstrem dari data harga produk. Ini berarti ada produk-produk dengan harga yang sangat tinggi yang tidak umum.
3. Kecenderungan Harga: Median yang lebih rendah dari rata-rata menunjukkan bahwa kebanyakan produk seblak dijual dengan harga lebih rendah dari rata-rata, tetapi beberapa produk mahal menarik rata-rata ke atas.



*--- Banyaknya Terjual ---*
- Mean (Rata-rata): 160.84
- Median: 80
- Standar Deviasi: 207.41
- Skewness: 1.36
- Kurtosis: 0.65

*Insight:*
1. Distribusi: Distribusi banyaknya produk terjual juga skewed positif dengan skewness sebesar 1.36. Ini menunjukkan bahwa sebagian besar produk terjual dalam jumlah yang relatif kecil, tetapi ada beberapa produk yang terjual dalam jumlah besar.
2. Outlier: Kurtosis yang mendekati 0.65 menunjukkan distribusi yang mendekati normal tetapi dengan sedikit puncak yang lebih rendah, menandakan adanya beberapa nilai outlier yang lebih tinggi tetapi tidak terlalu ekstrem.
3. Kecenderungan Penjualan: Median yang lebih rendah dari rata-rata menunjukkan bahwa sebagian besar produk terjual dalam jumlah lebih sedikit dari rata-rata, tetapi beberapa produk yang sangat laris menaikkan rata-rata.


*--- Rating ---*
- Mean (Rata-rata): 4.61
- Median: 4.9
- Standar Deviasi: 1.12
- Skewness: -3.84
- Kurtosis: 12.90

*Insight:*
1. Distribusi: Rating produk memiliki distribusi yang sangat tidak simetris (negatively skewed) karena nilai skewness sebesar -3.84. Ini menunjukkan bahwa sebagian besar produk memiliki rating yang sangat tinggi, dengan beberapa rating yang lebih rendah menarik distribusi ke arah negatif.
2. Outlier: Kurtosis yang tinggi (12.90) menunjukkan adanya outlier dalam data rating, dengan sebagian besar produk memiliki rating yang sangat tinggi.
3. Kecenderungan Rating: Median yang mendekati nilai maksimal (4.9) menunjukkan bahwa mayoritas produk seblak memiliki rating yang sangat baik, menandakan kepuasan pelanggan yang tinggi.


**Dari hasil perhitungan statistik deskriptif sebelumnya, ditemukan:**

- Harga produk seblak rata-rata adalah Rp 21.367 dengan median Rp 16.000 dan standar deviasi Rp 48.758.
- Banyaknya produk terjual rata-rata adalah 161 dengan median 80 dan standar deviasi 207.
- Rating produk rata-rata adalah 4.61 dengan median 4.9 dan standar deviasi 1.12.

### Potensi Pendapatan

Untuk menghitung potensi pendapatan, saya menggunakan data harga produk dan banyaknya terjual. Pendapatan per produk dihitung dengan mengalikan harga produk dengan banyaknya terjual. Dengan asumsi data terdistribusi normal, kita dapat menggunakan confidence interval 95% untuk mendapatkan estimasi pendapatan minimum dan maksimum.

In [40]:
# Menghitung potensi pendapatan 

import pandas as pd
from scipy.stats import norm

# Membaca data dari file CSV yang telah dibersihkan
data = pd.read_csv('data_tokped_seblak_clean.csv')


# Menghitung pendapatan per produk
data['Pendapatan'] = data['Harga Produk'] * data['Banyaknya Terjual']


# Menghitung rata-rata dan standar deviasi pendapatan
mean_pendapatan = data['Pendapatan'].mean()
std_pendapatan = data['Pendapatan'].std()

# Menghitung jumlah sampel
n = len(data)

In [41]:
# Menghitung nilai z untuk confidence level 95% (z-1.96)
z = 1.96

# Menghitung margin of error
margin_of_error = z * (std_pendapatan / (n ** 0.5))

# Menghitung confidence interval
ci_lower = mean_pendapatan - margin_of_error
ci_upper = mean_pendapatan + margin_of_error

ci_lower, ci_upper

(2562251.6488402104, 3358106.522904942)

Setelah menghitung interval kepercayaan untuk pendapatan bulanan dari penjualan produk seblak dengan confidence level 95%, kita memperoleh hasil berikut:

- Lower Value (Batas Bawah): 2,562,251.65 rupiah
- Upper Value (Batas Atas): 3,358,106.52 rupiah

Dengan confidence level 95%, kita dapat menyatakan bahwa pendapatan bulanan dari penjualan produk seblak di Tokopedia diperkirakan berada dalam rentang antara 2,562,251.65 rupiah hingga 3,358,106.52 rupiah. Ini berarti, dengan tingkat keyakinan 95%, kita yakin bahwa pendapatan aktual bulanan akan jatuh dalam rentang tersebut.

Rentang ini menunjukkan bahwa ada variasi yang cukup besar dalam pendapatan bulanan, yang bisa jadi disebabkan oleh faktor-faktor seperti variasi harga produk, volume penjualan yang berbeda, dan adanya produk dengan penjualan yang sangat tinggi (outlier).


Dengan potensi pendapatan maksimum yang mencapai lebih dari 3,3 juta rupiah, penjualan seblak di Tokopedia menunjukkan peluang bisnis yang cukup menjanjikan, khususnya jika strategi penjualan dapat meningkatkan volume penjualan atau harga produk rata-rata.

Untuk menentukan apakah ada perbedaan harga barang di Jabodetabek dan di luar Jabodetabek, perlu menggunakan uji hipotesis. 

Langkah-langkah yang akan kita lakukan meliputi:

- Menuliskan Hipotesis Null dan Alternatif
- Memilih Jenis Uji Hipotesis
- Menghitung Statistik Uji dan p-value
- Menarik Kesimpulan Berdasarkan Hasil Uji

1. Menuliskan Hipotesis Null dan Alternatif

    *Hipotesis Null (H0):* Tidak ada perbedaan signifikan antara harga barang di Jabodetabek dan di luar Jabodetabek. 

            H0: H Jabodetabek = H Luar Jabodetabek

    *Hipotesis Alternatif (Ha):* Ada perbedaan signifikan antara harga barang di Jabodetabek dan di luar Jabodetabek. 

            Ha: H Jabodetabek ≠ H Luar Jabodetabek

​
2. Memilih Jenis Uji Hipotesis

    Kami akan menggunakan uji t dua sampel (two-sample t-test) untuk menguji perbedaan rata-rata antara dua kelompok yang tidak berpasangan (independent samples).

3. Menghitung Statistik Uji dan p-value

    Langkah ini melibatkan pembagian data menjadi dua kelompok (Jabodetabek dan luar Jabodetabek), menghitung rata-rata dan standar deviasi masing-masing kelompok, dan kemudian melakukan uji t dua sampel.

In [6]:
# Import library
from scipy.stats import ttest_ind

# Memisahkan data berdasarkan lokasi
jabodetabek = data[data['Kota Toko'].str.contains('Jakarta|Bogor|Depok|Tangerang|Bekasi')]
non_jabodetabek = data[~data['Kota Toko'].str.contains('Jakarta|Bogor|Depok|Tangerang|Bekasi')]

# Melakukan uji-t dua sampel independen
t_stat, p_value = ttest_ind(jabodetabek['Harga Produk'], non_jabodetabek['Harga Produk'], equal_var=False)

# Menampilkan data
t_stat, p_value

(-0.02323380370481917, 0.9814774645764894)

- t-statistic: -0.02323380370481917
- p-value: 0.9814774645764894

**Analisis**
1. Nilai t-statistic:

    t-statistic yang sangat mendekati 0 (-0.023) menunjukkan bahwa perbedaan rata-rata harga antara Jabodetabek dan luar Jabodetabek sangat kecil.

2. Nilai p-value:

    p-value sebesar 0.981 sangat tinggi dan jauh di atas ambang batas umum 0.05. Ini berarti, probabilitas untuk mendapatkan hasil seperti ini atau lebih ekstrem jika hipotesis null benar sangat tinggi.

**Kesimpulan**

Karena p-value (0.981) lebih besar dari tingkat signifikansi 0.05, jadi kami gagal menolak hipotesis null. Ini berarti kami tidak memiliki bukti yang cukup untuk menyatakan bahwa terdapat perbedaan yang signifikan antara harga barang di Jabodetabek dan di luar Jabodetabek.

**Insight**
1. Harga Barang: Dari hasil analisis statistik, kami dapat menyimpulkan bahwa secara umum, harga barang di Jabodetabek dan di luar Jabodetabek tidak menunjukkan perbedaan yang signifikan.
2. Strategi Penetapan Harga: Informasi ini berguna bagi kami (penjual) dan distributor dalam menetapkan strategi harga. Karena tidak ada perbedaan signifikan dalam harga, strategi penetapan harga yang konsisten di berbagai lokasi dapat dipertimbangkan.
3. Faktor Lain: Meskipun tidak ada perbedaan yang signifikan dalam harga, kami mungkin perlu mempertimbangkan faktor lain seperti biaya pengiriman, ketersediaan produk, dan preferensi konsumen di lokasi yang berbeda untuk mengoptimalkan penjualan.

Selanjutnya, untuk mengetahui apakah orang lebih cenderung menyukai produk yang harganya murah, kami menggunakan uji korelasi antara harga produk dan rating produk.

Langkah Perhitungan:

1. Menghitung nilai korelasi dan p-value:
Kami akan menggunakan korelasi Pearson jika data terdistribusi normal, atau Spearman jika data tidak terdistribusi normal.
2. Analisis hasil:
    - Korelasi positif menunjukkan bahwa ketika harga naik, rating juga naik.
    - Korelasi negatif menunjukkan bahwa ketika harga naik, rating turun.
    - p-value yang kecil (biasanya < 0.05) menunjukkan bahwa hasil korelasi signifikan.

In [11]:
# Import libraries
import pandas as pd
from scipy.stats import skew, kurtosis, pearsonr, spearmanr

# Membaca data dari file CSV yang telah dibersihkan
data = pd.read_csv('data_tokped_seblak_clean.csv')

# Menghitung skewness dan kurtosis
harga_skewness = skew(data['Harga Produk'])
harga_kurtosis = kurtosis(data['Harga Produk'])

rating_skewness = skew(data['Rating'])
rating_kurtosis = kurtosis(data['Rating'])

# hasil perhitungan
harga_skewness, harga_kurtosis, rating_skewness, rating_kurtosis

(11.964782295450748, 151.0251693345549, -3.844934182411999, 12.900560972841207)

Dengan mempertimbangkan hasil dari uji skewness dan kurtosis yang menunjukkan bahwa data harga dan rating tidak terdistribusi normal (harga sangat skewed positif dan kurtosis tinggi, rating sangat skewed negatif dan kurtosis tinggi), kami akan menggunakan uji korelasi Spearman. Spearman cocok untuk data yang tidak terdistribusi normal.

In [14]:
# Menghitung korelasi Spearman antara harga produk dan rating
corr, p_value = spearmanr(data['Harga Produk'], data['Rating'])

# Tampilkan hasil
corr, p_value

(0.133776428041066, 0.010947088389750887)

Sesuai dengan hasil perhitungan: 

- Nilai Korelasi (corr): 0.134
- p-value: 0.011

**Kesimpulan**

Dari hasil korelasi Spearman, dapat disimpulkan bahwa ada kecenderungan konsumen memberikan rating yang sedikit lebih tinggi untuk produk dengan harga yang lebih tinggi, meskipun hubungannya lemah. Korelasi positif yang signifikan menunjukkan bahwa ketika harga produk seblak meningkat, rating yang diberikan oleh konsumen cenderung sedikit meningkat juga.

Ini memberikan insight bahwa harga produk mungkin mempengaruhi persepsi konsumen terhadap kualitas produk. Konsumen mungkin mengasosiasikan harga yang lebih tinggi dengan kualitas yang lebih baik, sehingga mereka memberikan rating yang lebih tinggi.

## E. Conclusion

Berdasarkan hasil analisis, dapat disimpulkan bahwa:

**Harga Produk dan Banyaknya Terjual**
- Harga Produk:
    - Mean: Rp 21,367.454
    - Median: Rp 16,000.000
    
    Harga produk menunjukkan variasi yang cukup besar, yang dapat dilihat dari perbedaan antara mean dan median.

- Banyaknya Terjual:
    - Mean: 160.84 produk
    - Median: 80 produk
    
    Variasi penjualan juga tinggi, menunjukkan bahwa beberapa produk terjual dalam jumlah yang jauh lebih tinggi dibandingkan dengan yang lain.


**Distribusi Data**

*Skewness dan Kurtosis:*

- Harga produk dan banyaknya terjual memiliki skewness positif yang cukup besar, menunjukkan bahwa data tidak berdistribusi normal dan memiliki banyak outlier.
- Rating memiliki skewness negatif yang tinggi, menandakan banyaknya rating yang mendekati nilai maksimum, dan distribusi data rating yang tidak simetris.


**Confidence Interval**

Confidence interval untuk harga produk adalah antara Rp 2,562,251.65 dan Rp 3,358,106.52, yang menunjukkan rentang pendapatan bulanan potensial dengan tingkat keyakinan 95%.


**Uji Hipotesis**

Hasil uji t menunjukkan bahwa tidak ada perbedaan signifikan dalam harga produk antara Jabodetabek dan luar Jabodetabek (p-value = 0.981). Dengan p-value yang tinggi, kami gagal menolak hipotesis nol yang menyatakan bahwa harga produk di dua wilayah tersebut tidak berbeda secara signifikan.


**Korelasi**

Harga dan Rating:

- Korelasi Spearman antara harga produk dan rating adalah 0.134 dengan p-value sebesar 0.011.
- Ini menunjukkan adanya hubungan positif yang lemah namun signifikan antara harga produk dan rating. Produk dengan harga lebih tinggi cenderung memiliki rating yang sedikit lebih tinggi.


#### **Kesimpulan Utama**
1. Variasi Harga dan Penjualan: Harga produk dan jumlah penjualan menunjukkan variasi yang signifikan, dengan banyaknya outlier yang mempengaruhi distribusi data.
2. Distribusi Rating: Rating produk cenderung sangat tinggi dan tidak simetris, menunjukkan bahwa konsumen cenderung memberikan rating yang baik.
3. Pendapatan Bulanan: Potensi pendapatan bulanan dari penjualan produk seblak berada dalam rentang yang cukup besar, menandakan adanya variasi yang signifikan dalam penjualan.
4. Perbedaan Harga Regional: Tidak ada perbedaan signifikan dalam harga produk antara Jabodetabek dan luar Jabodetabek.
Pengaruh Harga terhadap Rating: Terdapat hubungan positif yang signifikan antara harga produk dan rating, meskipun hubungan ini lemah.


#### **Langkah Selanjutnya**
1. Diperlukan **analisis lebih lanjut** untuk memahami faktor-faktor lain yang mempengaruhi penjualan produk seblak, seperti kualitas produk, promosi, dan faktor demografis.
2. Mengingat adanya korelasi positif antara harga dan rating, **penetapan harga yang tepat** bisa menjadi strategi untuk meningkatkan persepsi kualitas produk dan menarik lebih banyak pelanggan. Juga bisa dengan **menawarkan diskon** atau promosi untuk produk dengan harga lebih tinggi untuk meningkatkan penjualan dan rating.
3. **Dilakukan pengelolaan Outlier**